export const routePaths = {
  home: '/',

  // Explore
  explore: '/explore',
  exploreDistricts: '/explore/districts',
  exploreDistrictDetails: '/explore/districts/:districtId',
  exploreVillages: '/explore/villages',
  exploreVillageDetails: '/explore/villages/:villageId',
  exploreCrafts: '/explore/crafts',
  exploreCraftDetails: '/explore/crafts/:craftId',
  exploreProducers: '/explore/producers',
  exploreProducerDetails: '/explore/producers/:producerId',
  exploreUnesco: '/explore/unesco',
  exploreMuseum: '/explore/museum',

  // Marketplace
  marketplace: '/marketplace',
  marketplaceProducts: '/marketplace/products',
  marketplaceProductDetails: '/marketplace/products/:productId',
  marketplaceCategories: '/marketplace/categories',
  marketplaceWishlist: '/marketplace/wishlist',
  marketplaceCart: '/marketplace/cart',
  marketplaceCheckout: '/marketplace/checkout',
  marketplaceAuctions: '/marketplace/auctions',

  // Tourism
  tourism: '/tourism',
  tourismMap: '/tourism/map',
  tourismFestivals: '/tourism/festivals',
  tourismEvents: '/tourism/events',
  tourismVillages: '/tourism/villages',
  tourismRoutes: '/tourism/routes',
  tourismPassport: '/tourism/passport',
  tourismCuisines: '/tourism/cuisines',
  tourismServices: '/tourism/services',
  tourismServiceDetails: '/tourism/services/:serviceId',
  tourismBookings: '/tourism/bookings',
  tourismAiPlanner: '/tourism/ai-planner',

  // Academy
  academy: '/academy',
  academyCourseDetails: '/academy/courses/:courseId',
  academyMentors: '/academy/mentors',
  academyCertifications: '/academy/certifications',
  academyLearning: '/academy/learning',
  academyCertificates: '/academy/certificates',
  academyPortfolio: '/academy/portfolio',
  academyRoadmap: '/academy/roadmap',
  academyMentorshipRequests: '/academy/mentorship-requests',
  academyExamDetails: '/academy/exams/:examId',
  academyQuizDetails: '/academy/quizzes/:quizId',
  academyAssignmentDetails: '/academy/assignments/:assignmentId',
  academyLiveClasses: '/academy/live-classes',
  academyLiveClassDetails: '/academy/live-classes/:liveClassId',
  academySkillAssessments: '/academy/skill-assessments',

  // Research / Innovation Hub
  research: '/research',
  researchWorkspace: '/research/workspace',
  researchPublications: '/research/publications',
  researchHeritageDatabase: '/research/heritage-database',

  // Content
  news: '/news',
  newsDetails: '/news/:newsId',
  about: '/about',

  // Auth
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',

  // Dashboard (authenticated shell)
  dashboard: '/dashboard',
  dashboardExplore: '/dashboard/explore',
  dashboardMarketplace: '/dashboard/marketplace',
  dashboardTourism: '/dashboard/tourism',
  dashboardAcademy: '/dashboard/academy',
  dashboardCommunity: '/dashboard/community',
  dashboardAnalytics: '/dashboard/analytics',
  dashboardMessages: '/dashboard/messages',
  dashboardNotifications: '/dashboard/notifications',
  dashboardSettings: '/dashboard/settings',
  dashboardProfile: '/dashboard/profile',

  // Customer journey
  customer: '/customer',
  customerMarketplace: '/customer/marketplace',
  customerProductDetails: '/customer/products/:productId',
  customerCraftStory: '/customer/crafts/:craftId/story',
  customerProducerProfile: '/customer/producers/:producerId',
  customerProducerStory: '/customer/producers/:producerId/story',
  customerWorkshops: '/customer/workshops',
  customerWishlist: '/customer/wishlist',
  customerCart: '/customer/cart',
  customerCheckout: '/customer/checkout',
  customerOrderSuccess: '/customer/order-success',
  customerCustomOrder: '/customer/custom-order',
  customerLiveShopping: '/customer/live-shopping/:workshopId',
  customerAuctions: '/customer/auctions',
  customerAuctionDetails: '/customer/auctions/:auctionId',
  customerCommunity: '/customer/community',
  customerForum: '/customer/community/forum',
  customerQA: '/customer/community/qa',
  customerMessages: '/customer/messages',
  customerFollowing: '/customer/following',
  customerFavoriteVillages: '/customer/favorite-villages',
  customerOrders: '/customer/orders',
  customerOrderDetails: '/customer/orders/:orderId',
  customerReturns: '/customer/returns',
  customerRefunds: '/customer/refunds',
  customerNotifications: '/customer/notifications',
  customerAddresses: '/customer/addresses',
  customerHeritageCollection: '/customer/heritage-collection',
  customerPurchaseAnalytics: '/customer/purchase-analytics',
  customerImpactDashboard: '/customer/impact',
  customerHeritagePassport: '/customer/heritage-passport',
  customerAchievements: '/customer/achievements',
  customerBadges: '/customer/badges',
  customerAIInteriorPreview: '/customer/ai/interior-preview/:productId',
  customerAIFashionMatching: '/customer/ai/fashion-matching/:productId',
  customerAIGiftRecommendation: '/customer/ai/gift-recommendation',
  customerAISimilarProducts: '/customer/ai/similar-products/:productId',

  // Producer dashboard (backend role: Producer)
  producer: '/producer',
  producerContracts: '/producer/contracts',
  producerQuotations: '/producer/quotations',
  producerPartnerships: '/producer/partnerships',
  producerDesignCollaborations: '/producer/design-collaborations',
  producerProductDevelopment: '/producer/product-development',
  producerCsr: '/producer/csr-sponsorship',
  producerInvestments: '/producer/investment-opportunities',
  producerInventory: '/producer/inventory',
  producerOrders: '/producer/orders',
  producerSustainability: '/producer/sustainability',
  producerAiAssistant: '/producer/ai-assistant',

  // Business Partner dashboard (backend role: BusinessPartner)
  businessPartner: '/business-partner',
  businessPartnerProfile: '/business-partner/profile',
  businessPartnerContracts: '/business-partner/contracts',
  businessPartnerQuotations: '/business-partner/quotations',
  businessPartnerProcurements: '/business-partner/procurements',
  businessPartnerPartnerships: '/business-partner/partnerships',
  businessPartnerDesignCollaborations: '/business-partner/design-collaborations',
  businessPartnerProductDevelopment: '/business-partner/product-development',
  businessPartnerCsr: '/business-partner/csr-sponsorship',
  businessPartnerInvestments: '/business-partner/investment-opportunities',
  businessPartnerSupplierDiscovery: '/business-partner/supplier-discovery',
  businessPartnerSupplierMatching: '/business-partner/supplier-matching',
  businessPartnerProducerComparison: '/business-partner/producer-comparison',
  businessPartnerAnalytics: '/business-partner/analytics',
  businessPartnerAiIntelligence: '/business-partner/ai-intelligence',

  // Roles
  academyMember: '/academy-member',
  visitor: '/visitor',
  artisan: '/artisan',
  farmer: '/farmer',
  retailer: '/retailer',
  industryGarments: '/industry-garments',
  tourist: '/tourist',
  trainerMasterArtisan: '/trainer-master-artisan',
  trainerMasterArtisanPrograms: '/trainer-master-artisan/programs',
  apprenticeStudent: '/apprentice-student',
  government: '/government',
  ngo: '/ngo',
  researcher: '/researcher',
  exporter: '/exporter',
  logisticsPartner: '/logistics-partner',
  logisticsPartnerProfile: '/logistics-partner/profile',
  logisticsPartnerWarehouses: '/logistics-partner/warehouses',
  logisticsPartnerShipments: '/logistics-partner/shipments',
  logisticsPartnerStock: '/logistics-partner/warehouse-stock',
  logisticsPartnerPickups: '/logistics-partner/pickup-requests',
  logisticsPartnerReturns: '/logistics-partner/returns',
  logisticsPartnerRoutes: '/logistics-partner/routes',
  logisticsPartnerAiTools: '/logistics-partner/ai-tools',

  // Admin
  admin: '/admin',
  adminUsers: '/admin/users',
  adminHeritage: '/admin/heritage',
  adminMarketplace: '/admin/marketplace',
  adminCms: '/admin/cms',
  adminSecurity: '/admin/security',

  unauthorized: '/unauthorized',
  notFound: '*',
};
