export const routePaths = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  visitor: '/visitor',
  customer: '/customer',
  artisan: '/artisan',
  farmer: '/farmer',
  retailer: '/retailer',
  industryGarments: '/industry-garments',
  tourist: '/tourist',
  trainerMasterArtisan: '/trainer-master-artisan',
  apprenticeStudent: '/apprentice-student',
  government: '/government',
  ngo: '/ngo',
  researcher: '/researcher',
  exporter: '/exporter',
  logisticsPartner: '/logistics-partner',
  admin: '/admin',
  unauthorized: '/unauthorized',
  notFound: '*',
};
export const routePaths = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  admin: '/admin',
  unauthorized: '/unauthorized',
  notFound: '*',
};
