using System.Text.Json;
using ShilpoHubBD.Application.DTOs.Governance;
using ShilpoHubBD.Application.Exceptions;
using ShilpoHubBD.Application.Interfaces.Repositories;
using ShilpoHubBD.Application.Interfaces.Services;
using ShilpoHubBD.Domain.Constants;
using ShilpoHubBD.Domain.Entities.Governance;

namespace ShilpoHubBD.Application.Services.Governance;

public class ArtisanSupportService(IArtisanSupportRepository repository) : IArtisanSupportService
{
    public async Task<SupportOrganizationDto?> GetMyOrganizationAsync(Guid userId, CancellationToken ct) => (await repository.GetOrganizationByUserAsync(userId, ct))?.ToDto();
    public async Task<SupportOrganizationDto> UpsertOrganizationAsync(Guid userId, UpsertSupportOrganizationRequest r, CancellationToken ct)
    {
        Required(r.OrganizationName, r.OrganizationType, r.RegistrationNumber, r.RegistrationAuthority, r.OfficialEmail, r.OfficialPhone, r.Address, r.OrganizationDetails, r.RepresentativeName, r.RepresentativeDesignation, r.RepresentativeNid, r.RepresentativePhone);
        var p = await repository.GetOrganizationByUserAsync(userId, ct);
        if (await repository.RegistrationNumberExistsAsync(r.RegistrationNumber.Trim(), p?.Id, ct)) throw new ConflictException("This registration number is already in use.");
        var now = DateTime.UtcNow;
        if (p is null) { p = new SupportOrganizationProfile { Id = Guid.NewGuid(), UserId = userId, CreatedAt = now }; await repository.AddOrganizationAsync(p, ct); }
        if (p.Status == OrganizationVerificationStatus.Approved && r.RegistrationNumber.Trim() != p.RegistrationNumber) p.Status = OrganizationVerificationStatus.Pending;
        p.OrganizationName=r.OrganizationName.Trim(); p.OrganizationType=r.OrganizationType.Trim(); p.RegistrationNumber=r.RegistrationNumber.Trim(); p.RegistrationAuthority=r.RegistrationAuthority.Trim();
        p.RegistrationDocumentUrl=r.RegistrationDocumentUrl?.Trim() ?? p.RegistrationDocumentUrl; p.OfficialEmail=r.OfficialEmail.Trim(); p.OfficialPhone=r.OfficialPhone.Trim(); p.Address=r.Address.Trim();
        p.OperatingDistrictsJson=JsonSerializer.Serialize(r.OperatingDistricts.Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x.Trim()).Distinct()); p.OrganizationDetails=r.OrganizationDetails.Trim();
        p.RepresentativeName=r.RepresentativeName.Trim(); p.RepresentativeDesignation=r.RepresentativeDesignation.Trim(); p.RepresentativeNid=r.RepresentativeNid.Trim(); p.RepresentativePhone=r.RepresentativePhone.Trim(); p.UpdatedAt=now;
        if (r.SubmitForReview) { if (string.IsNullOrWhiteSpace(p.RegistrationDocumentUrl)) throw new ConflictException("Upload the registration certificate before submitting."); p.Status=OrganizationVerificationStatus.Pending; p.ReviewNotes=null; }
        await repository.SaveChangesAsync(ct); return p.ToDto();
    }
    public async Task<IReadOnlyList<SupportOrganizationDto>> GetOrganizationsAsync(CancellationToken ct) => (await repository.GetOrganizationsAsync(ct)).Select(x=>x.ToDto()).ToList();
    public async Task<SupportOrganizationDto> ReviewOrganizationAsync(Guid adminId, Guid id, ReviewSupportOrganizationRequest r, CancellationToken ct)
    { var p=await repository.GetOrganizationAsync(id,ct)??throw new NotFoundException("Organization profile not found."); p.Status=r.Approved?OrganizationVerificationStatus.Approved:OrganizationVerificationStatus.Rejected; p.ReviewedByUserId=adminId;p.ReviewedAt=DateTime.UtcNow;p.ReviewNotes=r.Notes?.Trim();p.UpdatedAt=DateTime.UtcNow;await repository.SaveChangesAsync(ct);return p.ToDto(); }
    public async Task<IReadOnlyList<SupportUserOptionDto>> GetArtisansAsync(CancellationToken ct) => (await repository.GetUsersInRoleAsync(RoleNames.Producer,ct)).Select(x=>new SupportUserOptionDto(x.Id,x.FullName,x.Email)).ToList();
    public async Task<IReadOnlyList<SupportUserOptionDto>> GetApprovedOrganizationsAsync(CancellationToken ct) => (await repository.GetOrganizationsAsync(ct)).Where(x=>x.Status==OrganizationVerificationStatus.Approved).Select(x=>new SupportUserOptionDto(x.UserId,x.OrganizationName,x.RegistrationNumber)).ToList();
    public async Task<IReadOnlyList<ArtisanSupportCaseDto>> GetCasesAsync(Guid userId,bool isAdmin,bool isGovernment,CancellationToken ct)=>(await repository.GetCasesAsync(userId,isAdmin,isGovernment,ct)).Select(ToDto).ToList();
    public async Task<ArtisanSupportCaseDto> GetCaseAsync(Guid userId,Guid id,bool isAdmin,bool isGovernment,CancellationToken ct){var c=await Load(id,ct);EnsureCanView(c,userId,isAdmin,isGovernment);return ToDto(c);}
    public async Task<ArtisanSupportCaseDto> CreateCaseAsync(Guid userId,bool isGovernment,CreateArtisanSupportCaseRequest r,CancellationToken ct)
    {
        Required(r.ProblemTitle,r.ProblemDescription); var artisanId=isGovernment?r.ArtisanUserId??throw new ConflictException("Select an artisan."):userId;
        var artisan=await repository.GetUserAsync(artisanId,ct)??throw new NotFoundException("Artisan not found."); if(!artisan.UserRoles.Any(x=>x.Role.Name==RoleNames.Producer))throw new ConflictException("Selected user is not an artisan/producer.");
        Guid? org=null;if(isGovernment){var p=await ApprovedOrg(userId,ct);org=p.UserId;}
        var now=DateTime.UtcNow; var c=new ArtisanSupportCase{Id=Guid.NewGuid(),CaseNumber=$"ASC-{now:yyyyMM}-{Random.Shared.Next(10000,99999)}",ArtisanUserId=artisanId,OrganizationUserId=org,CreatedByUserId=userId,ProblemTitle=r.ProblemTitle.Trim(),ProblemDescription=r.ProblemDescription.Trim(),District=r.District?.Trim(),Craft=r.Craft?.Trim(),Status=isGovernment?ArtisanSupportCaseStatus.Accepted:ArtisanSupportCaseStatus.Submitted,CreatedAt=now,UpdatedAt=now};
        await repository.AddCaseAsync(c,ct);await repository.SaveChangesAsync(ct);return ToDto(await Load(c.Id,ct));
    }
    public async Task<ArtisanSupportCaseDto> AssignAsync(Guid adminId,Guid id,AssignArtisanSupportCaseRequest r,CancellationToken ct){var c=await Load(id,ct);var p=await repository.GetOrganizationByUserAsync(r.OrganizationUserId,ct);if(p?.Status!=OrganizationVerificationStatus.Approved)throw new ConflictException("Assign only to a verified organization.");c.OrganizationUserId=r.OrganizationUserId;c.AssignedByAdminUserId=adminId;c.AssignedOfficerName=r.OfficerName?.Trim();c.AssignedOfficerPhone=r.OfficerPhone?.Trim();c.MonitoringDueAt=r.InspectionDueAt;c.ReportDueAt=r.ReportDueAt;c.Status=ArtisanSupportCaseStatus.Assigned;c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> AcceptAsync(Guid userId,Guid id,CancellationToken ct){await ApprovedOrg(userId,ct);var c=await Load(id,ct);if(c.OrganizationUserId is not null&&c.OrganizationUserId!=userId)throw new UnauthorizedAccessException("This case belongs to another organization.");c.OrganizationUserId=userId;c.Status=ArtisanSupportCaseStatus.InspectionPending;c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> InspectAsync(Guid userId,Guid id,RecordSupportInspectionRequest r,CancellationToken ct){var c=await Managed(id,userId,ct);var result=Parse<ArtisanInspectionResult>(r.Result);Required(r.IdentityFindings,r.WorkshopFindings,r.CraftAuthenticityFindings,r.ProductToolsFindings,r.ProblemFindings,r.RootCause);c.InspectionResult=result;c.IdentityFindings=r.IdentityFindings.Trim();c.WorkshopFindings=r.WorkshopFindings.Trim();c.CraftAuthenticityFindings=r.CraftAuthenticityFindings.Trim();c.ProductToolsFindings=r.ProductToolsFindings.Trim();c.ProblemFindings=r.ProblemFindings.Trim();c.RootCause=r.RootCause.Trim();c.Status=ArtisanSupportCaseStatus.Inspected;if(result==ArtisanInspectionResult.FraudSuspected){c.IsFlagged=true;c.FlagReason="Field inspection marked fraud suspected.";}c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> PlanAsync(Guid userId,Guid id,RecordSupportPlanRequest r,CancellationToken ct){var c=await Managed(id,userId,ct);if(c.InspectionResult==ArtisanInspectionResult.NotInspected)throw new ConflictException("Complete field inspection first.");Required(r.SupportPlan,r.FundingSourceType,r.FundingSourceName);c.SupportKind=Parse<ArtisanSupportKind>(r.SupportKind);c.SupportPlan=r.SupportPlan.Trim();c.FundingSourceType=r.FundingSourceType.Trim();c.FundingSourceName=r.FundingSourceName.Trim();c.SupportAmount=r.SupportAmount;c.SupportValueDescription=r.SupportValueDescription?.Trim();c.Status=ArtisanSupportCaseStatus.SupportPlanned;c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> RecordProvidedAsync(Guid userId,Guid id,RecordSupportProvidedRequest r,CancellationToken ct){var c=await Managed(id,userId,ct);if(string.IsNullOrWhiteSpace(c.SupportPlan))throw new ConflictException("Create a support plan first.");c.SupportProvidedAt=r.ProvidedAt.ToUniversalTime();c.SupportAmount=r.SupportAmount??c.SupportAmount;c.SupportValueDescription=r.SupportValueDescription?.Trim()??c.SupportValueDescription;c.MonitoringDueAt=r.MonitoringDueAt?.ToUniversalTime();c.ReportDueAt=r.ReportDueAt.ToUniversalTime();c.Status=ArtisanSupportCaseStatus.SupportProvided;c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> ConfirmAsync(Guid artisanId,Guid id,ConfirmArtisanSupportRequest r,CancellationToken ct){var c=await Load(id,ct);if(c.ArtisanUserId!=artisanId)throw new UnauthorizedAccessException("Only the artisan in this case can confirm receipt.");if(c.SupportProvidedAt is null)throw new ConflictException("Support delivery has not been recorded.");c.ArtisanConfirmation=Parse<ArtisanSupportConfirmation>(r.Confirmation);c.ArtisanConfirmationNotes=r.Notes?.Trim();if(c.ArtisanConfirmation is ArtisanSupportConfirmation.DidNotReceive or ArtisanSupportConfirmation.ReportProblem){c.HasDispute=true;c.IsFlagged=true;c.FlagReason="Artisan disputed the recorded support delivery.";}c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> MonitorAsync(Guid userId,Guid id,AddSupportMonitoringRequest r,CancellationToken ct){var c=await Managed(id,userId,ct);if(c.SupportProvidedAt is null)throw new ConflictException("Record support delivery before monitoring.");Required(r.ProductionStatus);c.MonitoringEntries.Add(new ArtisanSupportMonitoring{Id=Guid.NewGuid(),CaseId=c.Id,RecordedByUserId=userId,FollowedUpAt=r.FollowUpDate.ToUniversalTime(),ProductionStatus=r.ProductionStatus.Trim(),IncomeMarketImprovement=r.IncomeMarketImprovement?.Trim(),EquipmentCondition=r.EquipmentCondition?.Trim(),ProblemSolved=r.ProblemSolved,NewIssues=r.NewIssues?.Trim(),Notes=r.Notes?.Trim(),CreatedAt=DateTime.UtcNow});c.Status=ArtisanSupportCaseStatus.Monitoring;c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> SubmitReportAsync(Guid userId,Guid id,SubmitSupportReportRequest r,CancellationToken ct){var c=await Managed(id,userId,ct);if(c.SupportProvidedAt is null)throw new ConflictException("Record support delivery before submitting the final report.");if(c.MonitoringEntries.Count==0)throw new ConflictException("Record at least one monitoring follow-up before submitting the final report.");if(c.ArtisanConfirmation==ArtisanSupportConfirmation.Pending)throw new ConflictException("The artisan must confirm the support before the final report is submitted.");Required(r.OriginalProblem,r.VerificationFindings,r.ActionTaken,r.FundingSupportSource,r.ReceiptsEvidenceSummary,r.ArtisanConfirmationSummary,r.MonitoringResult,r.FinalOutcome,r.Recommendation);var report=c.FinalReport??new ArtisanSupportReport{Id=Guid.NewGuid(),CaseId=c.Id};report.OriginalProblem=r.OriginalProblem.Trim();report.VerificationFindings=r.VerificationFindings.Trim();report.ActionTaken=r.ActionTaken.Trim();report.FundingSupportSource=r.FundingSupportSource.Trim();report.AmountValueUsed=r.AmountValueUsed;report.ReceiptsEvidenceSummary=r.ReceiptsEvidenceSummary.Trim();report.ArtisanConfirmationSummary=r.ArtisanConfirmationSummary.Trim();report.MonitoringResult=r.MonitoringResult.Trim();report.FinalOutcome=r.FinalOutcome.Trim();report.Recommendation=r.Recommendation.Trim();report.ReviewStatus=SupportReportReviewStatus.WaitingReview;report.SubmittedByUserId=userId;report.SubmittedAt=DateTime.UtcNow;c.FinalReport=report;c.Status=ArtisanSupportCaseStatus.ReportSubmitted;c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> ReviewReportAsync(Guid adminId,Guid id,ReviewSupportReportRequest r,CancellationToken ct){var c=await Load(id,ct);var report=c.FinalReport??throw new ConflictException("The organization must submit its report before this case can be resolved.");var action=r.Action.Trim().ToLowerInvariant();report.ReviewStatus=action switch{"accept"=>SupportReportReviewStatus.Accepted,"clarify"=>SupportReportReviewStatus.ClarificationRequested,"flag"=>SupportReportReviewStatus.Flagged,_=>throw new ConflictException("Action must be accept, clarify, or flag.")};report.AdminReviewNotes=r.Notes?.Trim();report.ReviewedByUserId=adminId;report.ReviewedAt=DateTime.UtcNow;c.Status=action=="accept"?ArtisanSupportCaseStatus.Closed:ArtisanSupportCaseStatus.ClarificationRequested;if(action=="flag"){c.IsFlagged=true;c.FlagReason=r.Notes?.Trim()??"Report flagged by Admin.";}c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> FlagAsync(Guid adminId,Guid id,FlagSupportCaseRequest r,CancellationToken ct){Required(r.Reason);var c=await Load(id,ct);c.IsFlagged=true;c.FlagReason=r.Reason.Trim();c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportCaseDto> AddEvidenceAsync(Guid userId,Guid id,bool isAdmin,CreateSupportEvidenceRequest r,CancellationToken ct){var c=await Load(id,ct);if(!isAdmin&&c.ArtisanUserId!=userId&&c.OrganizationUserId!=userId)throw new UnauthorizedAccessException("You cannot add evidence to this case.");Required(r.FileUrl,r.FileName,r.ContentType);c.Evidence.Add(new ArtisanSupportEvidence{Id=Guid.NewGuid(),CaseId=id,Stage=Parse<SupportEvidenceStage>(r.Stage),FileUrl=r.FileUrl.Trim(),FileName=r.FileName.Trim(),ContentType=r.ContentType.Trim(),Caption=r.Caption?.Trim(),UploadedByUserId=userId,CreatedAt=DateTime.UtcNow});c.UpdatedAt=DateTime.UtcNow;return await Save(c,ct);}
    public async Task<ArtisanSupportDashboardDto> DashboardAsync(Guid userId,bool isAdmin,bool isGovernment,CancellationToken ct){var cases=await repository.GetCasesAsync(userId,isAdmin,isGovernment,ct);var orgs=isAdmin?await repository.GetOrganizationsAsync(ct):[];var now=DateTime.UtcNow;return new(cases.Count(x=>x.Status is not ArtisanSupportCaseStatus.Closed and not ArtisanSupportCaseStatus.Rejected),cases.Count(x=>x.Status is ArtisanSupportCaseStatus.Assigned or ArtisanSupportCaseStatus.Accepted or ArtisanSupportCaseStatus.InspectionPending),cases.Count(x=>x.InspectionResult is ArtisanInspectionResult.Verified or ArtisanInspectionResult.PartiallyVerified),cases.Count(x=>x.Status is ArtisanSupportCaseStatus.SupportPlanned or ArtisanSupportCaseStatus.SupportInProgress or ArtisanSupportCaseStatus.SupportProvided),cases.Count(x=>x.Status==ArtisanSupportCaseStatus.Monitoring),cases.Count(x=>x.SupportProvidedAt!=null&&x.FinalReport==null),cases.Count(x=>x.FinalReport!=null),cases.Where(x=>x.SupportProvidedAt!=null).Select(x=>x.ArtisanUserId).Distinct().Count(),orgs.Count(x=>x.Status==OrganizationVerificationStatus.Pending),orgs.Count(x=>x.Status==OrganizationVerificationStatus.Approved),cases.Count(x=>x.FinalReport?.ReviewStatus==SupportReportReviewStatus.WaitingReview),cases.Count(x=>x.ReportDueAt<now&&x.FinalReport==null),cases.Count(x=>x.HasDispute),cases.Count(x=>x.IsFlagged));}

    private async Task<SupportOrganizationProfile> ApprovedOrg(Guid userId,CancellationToken ct){var p=await repository.GetOrganizationByUserAsync(userId,ct)??throw new ConflictException("Complete your organization registration first.");if(p.Status!=OrganizationVerificationStatus.Approved)throw new ConflictException("Admin verification is required before managing artisan cases.");return p;}
    private async Task<ArtisanSupportCase> Managed(Guid id,Guid userId,CancellationToken ct){await ApprovedOrg(userId,ct);var c=await Load(id,ct);if(c.OrganizationUserId!=userId)throw new UnauthorizedAccessException("This case is not assigned to your organization.");return c;}
    private async Task<ArtisanSupportCase> Load(Guid id,CancellationToken ct)=>await repository.GetCaseAsync(id,ct)??throw new NotFoundException("Artisan support case not found.");
    private static void EnsureCanView(ArtisanSupportCase c,Guid userId,bool admin,bool govt){if(!admin&&c.ArtisanUserId!=userId&&(!govt||c.OrganizationUserId!=userId))throw new UnauthorizedAccessException("You cannot view this case.");}
    private async Task<ArtisanSupportCaseDto> Save(ArtisanSupportCase c,CancellationToken ct){await repository.SaveChangesAsync(ct);return ToDto(await Load(c.Id,ct));}
    private static T Parse<T>(string value) where T:struct,Enum=>Enum.TryParse<T>(value,true,out var result)?result:throw new ConflictException($"Invalid {typeof(T).Name} value.");
    private static void Required(params string?[] values){if(values.Any(string.IsNullOrWhiteSpace))throw new ConflictException("Complete all required fields.");}
    private static ArtisanSupportCaseDto ToDto(ArtisanSupportCase c)=>new(){Id=c.Id,CaseNumber=c.CaseNumber,ArtisanUserId=c.ArtisanUserId,ArtisanName=c.Artisan?.FullName??"Artisan",OrganizationUserId=c.OrganizationUserId,OrganizationName=c.Organization?.FullName,AssignedByAdmin=c.AssignedByAdminUserId.HasValue,ProblemTitle=c.ProblemTitle,ProblemDescription=c.ProblemDescription,District=c.District,Craft=c.Craft,AssignedOfficerName=c.AssignedOfficerName,AssignedOfficerPhone=c.AssignedOfficerPhone,InspectionResult=c.InspectionResult.ToString(),IdentityFindings=c.IdentityFindings,WorkshopFindings=c.WorkshopFindings,CraftAuthenticityFindings=c.CraftAuthenticityFindings,ProductToolsFindings=c.ProductToolsFindings,ProblemFindings=c.ProblemFindings,RootCause=c.RootCause,SupportPlan=c.SupportPlan,SupportKind=c.SupportKind?.ToString(),FundingSourceType=c.FundingSourceType,FundingSourceName=c.FundingSourceName,SupportAmount=c.SupportAmount,SupportValueDescription=c.SupportValueDescription,SupportProvidedAt=c.SupportProvidedAt,ArtisanConfirmation=c.ArtisanConfirmation.ToString(),ArtisanConfirmationNotes=c.ArtisanConfirmationNotes,HasDispute=c.HasDispute,IsFlagged=c.IsFlagged,FlagReason=c.FlagReason,MonitoringDueAt=c.MonitoringDueAt,ReportDueAt=c.ReportDueAt,Status=c.Status.ToString(),CreatedAt=c.CreatedAt,UpdatedAt=c.UpdatedAt,Evidence=c.Evidence.OrderByDescending(x=>x.CreatedAt).Select(x=>new SupportEvidenceDto(x.Id,x.Stage.ToString(),x.FileUrl,x.FileName,x.ContentType,x.Caption,x.CreatedAt)).ToList(),Monitoring=c.MonitoringEntries.OrderByDescending(x=>x.FollowedUpAt).Select(x=>new SupportMonitoringDto(x.Id,x.FollowedUpAt,x.ProductionStatus,x.IncomeMarketImprovement,x.EquipmentCondition,x.ProblemSolved,x.NewIssues,x.Notes,x.CreatedAt)).ToList(),FinalReport=c.FinalReport is null?null:new SupportFinalReportDto(c.FinalReport.Id,c.FinalReport.OriginalProblem,c.FinalReport.VerificationFindings,c.FinalReport.ActionTaken,c.FinalReport.FundingSupportSource,c.FinalReport.AmountValueUsed,c.FinalReport.ReceiptsEvidenceSummary,c.FinalReport.ArtisanConfirmationSummary,c.FinalReport.MonitoringResult,c.FinalReport.FinalOutcome,c.FinalReport.Recommendation,c.FinalReport.ReviewStatus.ToString(),c.FinalReport.AdminReviewNotes,c.FinalReport.SubmittedAt,c.FinalReport.ReviewedAt)};
}

internal static class ArtisanSupportMappings
{
    public static SupportOrganizationDto ToDto(this SupportOrganizationProfile p)=>new(p.Id,p.UserId,p.OrganizationName,p.OrganizationType,p.RegistrationNumber,p.RegistrationAuthority,p.RegistrationDocumentUrl,p.OfficialEmail,p.OfficialPhone,p.Address,JsonSerializer.Deserialize<List<string>>(p.OperatingDistrictsJson)??[],p.OrganizationDetails,p.RepresentativeName,p.RepresentativeDesignation,p.RepresentativeNid,p.RepresentativePhone,p.Status.ToString(),p.ReviewNotes,p.UpdatedAt);
}

