import { useState } from 'react';
import { AsyncState, Badge, Button, PageHeader } from '../../components/ui';
import MutationFeedback from '../../components/ui/MutationFeedback';
import { useSupportCases, useArtisanSupportMutations } from '../../hooks/useArtisanSupport';

const input='w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm';
export default function SupportCases(){const query=useSupportCases();const actions=useArtisanSupportMutations();const [show,setShow]=useState(false);const [form,setForm]=useState({problemTitle:'',problemDescription:'',district:'',craft:''});const [confirm,setConfirm]=useState({});
 const create=(e)=>{e.preventDefault();actions.createCase.mutate({...form,artisanUserId:null},{onSuccess:()=>{setShow(false);setForm({problemTitle:'',problemDescription:'',district:'',craft:''});}})};
 return <div><PageHeader title="Artisan support requests" description="Ask a verified NGO or Government organization for help, follow the case, and confirm exactly what you received." action={<Button onClick={()=>setShow(v=>!v)}>{show?'Cancel':'Request support'}</Button>}/>
 <MutationFeedback mutation={actions.createCase} successMessage="Support request submitted." /><MutationFeedback mutation={actions.confirm} successMessage="Your confirmation was recorded. A denial or problem is automatically sent to Admin for review." />
 {show&&<form onSubmit={create} className="mb-5 grid gap-3 rounded-xl border border-border bg-surface p-4 md:grid-cols-2"><input aria-label="Problem title" required className={input} placeholder="Problem title" value={form.problemTitle} onChange={e=>setForm(p=>({...p,problemTitle:e.target.value}))}/><input aria-label="District" className={input} placeholder="District" value={form.district} onChange={e=>setForm(p=>({...p,district:e.target.value}))}/><input aria-label="Craft" className={input} placeholder="Craft" value={form.craft} onChange={e=>setForm(p=>({...p,craft:e.target.value}))}/><textarea aria-label="Problem details" required rows={3} className={`${input} md:col-span-2`} placeholder="Explain the issue, current impact, and support needed" value={form.problemDescription} onChange={e=>setForm(p=>({...p,problemDescription:e.target.value}))}/><Button className="md:col-span-2">Submit request</Button></form>}
 <AsyncState isLoading={query.isLoading} isError={query.isError} error={query.error}><div className="space-y-3">{(query.data||[]).map(c=><article key={c.id} className="rounded-xl border border-border bg-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold text-primary">{c.caseNumber}</p><h2 className="font-semibold text-heading">{c.problemTitle}</h2><p className="text-sm text-body/60">{c.organizationName||'Waiting for an organization'} · {c.craft||'Craft not set'}</p></div><Badge tone={c.status==='Closed'?'success':'neutral'}>{c.status}</Badge></div><p className="mt-3 text-sm">{c.problemDescription}</p>{c.supportProvidedAt&&c.artisanConfirmation==='Pending'&&<div className="mt-4 rounded-lg border border-primary/20 bg-primary/5 p-4"><p className="mb-2 text-sm font-semibold">Confirm the support recorded by the organization</p><div className="flex flex-wrap gap-2"><select aria-label="Support confirmation" className={input} value={confirm[c.id]?.confirmation||''} onChange={e=>setConfirm(p=>({...p,[c.id]:{...p[c.id],confirmation:e.target.value}}))}><option value="">Choose confirmation</option>{['Received','PartiallyReceived','DidNotReceive','ReportProblem'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Confirmation notes" className={input} placeholder="Notes (recommended for a problem)" value={confirm[c.id]?.notes||''} onChange={e=>setConfirm(p=>({...p,[c.id]:{...p[c.id],notes:e.target.value}}))}/><Button disabled={!confirm[c.id]?.confirmation} onClick={()=>actions.confirm.mutate({id:c.id,payload:confirm[c.id]})}>Submit confirmation</Button></div></div>}{c.hasDispute&&<p className="mt-3 text-sm font-semibold text-red-600">Your dispute is awaiting Admin review.</p>}</article>)}{!(query.data||[]).length&&<p className="text-sm text-body/60">No support requests yet.</p>}</div></AsyncState></div>}

