import { useState } from 'react';
import { AsyncState, Badge, Button, PageHeader } from '../../components/ui';
import MutationFeedback from '../../components/ui/MutationFeedback';
import { useSupportArtisans, useSupportCases, useSupportDashboard, useSupportOrganization, useArtisanSupportMutations } from '../../hooks/useArtisanSupport';

const input = 'w-full rounded-lg border border-border bg-background px-3 py-2 text-sm';
const kinds = ['MoneyGrant','ToolsEquipment','RawMaterials','Training','MarketplaceBusinessSupport','WorkshopRepair','HeritagePreservationSupport','Other'];
const statusTone = (s) => s === 'Closed' ? 'success' : s?.includes('Report') ? 'secondary' : 'neutral';
const Labeled = ({ label, children }) => <label className="text-xs font-semibold uppercase tracking-wide text-body/70"><span className="mb-1 block">{label}</span>{children}</label>;
const Text = ({ label, value, onChange, area = false, required = true, type = 'text' }) => <Labeled label={label}>{area ? <textarea aria-label={label} required={required} rows={2} className={input} value={value} onChange={(e) => onChange(e.target.value)} /> : <input aria-label={label} required={required} type={type} className={input} value={value} onChange={(e) => onChange(e.target.value)} />}</Labeled>;

function ActionPanel({ selected, actions }) {
  const [step, setStep] = useState('inspection');
  const [evidence, setEvidence] = useState({ file: null, stage: 'Inspection', caption: '' });
  const [inspection, setInspection] = useState({ result:'Verified',identityFindings:'',workshopFindings:'',craftAuthenticityFindings:'',productToolsFindings:'',problemFindings:'',rootCause:'' });
  const [plan, setPlan] = useState({ supportKind:'ToolsEquipment',supportPlan:'',fundingSourceType:'NGO donor/project',fundingSourceName:'',supportAmount:'',supportValueDescription:'' });
  const [provided, setProvided] = useState({ providedAt:new Date().toISOString().slice(0,10),supportAmount:'',supportValueDescription:'',monitoringDueAt:'',reportDueAt:'' });
  const [monitor, setMonitor] = useState({ followUpDate:new Date().toISOString().slice(0,10),productionStatus:'',incomeMarketImprovement:'',equipmentCondition:'',problemSolved:false,newIssues:'',notes:'' });
  const [report, setReport] = useState({ originalProblem:selected.problemDescription,verificationFindings:'',actionTaken:'',fundingSupportSource:'',amountValueUsed:'',receiptsEvidenceSummary:'',artisanConfirmationSummary:selected.artisanConfirmation,monitoringResult:'',finalOutcome:'',recommendation:'' });
  const change = (setter) => (key, value) => setter((p) => ({ ...p, [key]: value }));
  const submit = (e, mutation, payload) => { e.preventDefault(); mutation.mutate({ id:selected.id, payload:{ ...payload, supportAmount:payload.supportAmount===''?null:Number(payload.supportAmount), amountValueUsed:payload.amountValueUsed===''?null:Number(payload.amountValueUsed), providedAt:payload.providedAt?new Date(payload.providedAt).toISOString():undefined, monitoringDueAt:payload.monitoringDueAt?new Date(payload.monitoringDueAt).toISOString():null, reportDueAt:payload.reportDueAt?new Date(payload.reportDueAt).toISOString():undefined, followUpDate:payload.followUpDate?new Date(payload.followUpDate).toISOString():undefined } }); };
  const tabs=[['inspection','Inspection'],['plan','Support plan'],['provided','Delivery'],['monitor','Monitoring'],['report','Final report']];
  return <section className="mt-4 rounded-xl border border-border bg-surface p-4">
    <div className="mb-5 rounded-lg border border-border bg-background p-3"><p className="mb-2 text-sm font-semibold">Photos, documents and receipts</p><div className="flex flex-wrap gap-2"><select aria-label="Evidence stage" className={input} value={evidence.stage} onChange={(e)=>setEvidence(p=>({...p,stage:e.target.value}))}>{['Inspection','SupportDelivery','Monitoring','FinalReport','Receipt'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Evidence caption" className={input} placeholder="Caption" value={evidence.caption} onChange={(e)=>setEvidence(p=>({...p,caption:e.target.value}))}/><input aria-label="Evidence file" className={input} type="file" accept=".pdf,image/jpeg,image/png,image/webp" onChange={(e)=>setEvidence(p=>({...p,file:e.target.files?.[0]||null}))}/><Button type="button" disabled={!evidence.file||actions.uploadEvidence.isPending} onClick={()=>actions.uploadEvidence.mutate({id:selected.id,...evidence},{onSuccess:()=>setEvidence({file:null,stage:'Inspection',caption:''})})}>Upload evidence</Button></div>{selected.evidence?.length>0&&<div className="mt-2 flex flex-wrap gap-2">{selected.evidence.map(x=><a key={x.id} href={x.fileUrl} target="_blank" rel="noreferrer" className="rounded-full bg-primary/5 px-3 py-1 text-xs text-primary underline">{x.stage}: {x.caption||x.fileName}</a>)}</div>}</div>
    <div className="mb-4 flex flex-wrap gap-2">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setStep(id)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${step===id?'bg-primary text-white':'bg-primary/5 text-primary'}`}>{label}</button>)}</div>
    {step==='inspection'&&<form className="grid gap-3 md:grid-cols-2" onSubmit={(e)=>submit(e,actions.inspect,inspection)}><Labeled label="Result"><select aria-label="Inspection result" className={input} value={inspection.result} onChange={(e)=>change(setInspection)('result',e.target.value)}>{['Verified','PartiallyVerified','InsufficientEvidence','FraudSuspected'].map(x=><option key={x}>{x}</option>)}</select></Labeled>{['identityFindings','workshopFindings','craftAuthenticityFindings','productToolsFindings','problemFindings','rootCause'].map(k=><Text key={k} label={k.replace(/([A-Z])/g,' $1')} area value={inspection[k]} onChange={(v)=>change(setInspection)(k,v)} />)}<Button className="md:col-span-2">Save inspection</Button></form>}
    {step==='plan'&&<form className="grid gap-3 md:grid-cols-2" onSubmit={(e)=>submit(e,actions.plan,plan)}><Labeled label="Support type"><select aria-label="Support type" className={input} value={plan.supportKind} onChange={(e)=>change(setPlan)('supportKind',e.target.value)}>{kinds.map(x=><option key={x}>{x}</option>)}</select></Labeled><Labeled label="Funding source type"><select aria-label="Funding source type" className={input} value={plan.fundingSourceType} onChange={(e)=>change(setPlan)('fundingSourceType',e.target.value)}>{['NGO own fund','NGO donor/project','Government programme','CSR/external partner'].map(x=><option key={x}>{x}</option>)}</select></Labeled><Text label="Funding source name" value={plan.fundingSourceName} onChange={(v)=>change(setPlan)('fundingSourceName',v)} /><Text label="Amount/value" type="number" required={false} value={plan.supportAmount} onChange={(v)=>change(setPlan)('supportAmount',v)} /><Text label="Support plan" area value={plan.supportPlan} onChange={(v)=>change(setPlan)('supportPlan',v)} /><Text label="Value description" area required={false} value={plan.supportValueDescription} onChange={(v)=>change(setPlan)('supportValueDescription',v)} /><Button className="md:col-span-2">Save support plan</Button></form>}
    {step==='provided'&&<form className="grid gap-3 md:grid-cols-2" onSubmit={(e)=>submit(e,actions.provided,provided)}><Text label="Provided date" type="date" value={provided.providedAt} onChange={(v)=>change(setProvided)('providedAt',v)} /><Text label="Amount used" type="number" required={false} value={provided.supportAmount} onChange={(v)=>change(setProvided)('supportAmount',v)} /><Text label="Monitoring due" type="date" required={false} value={provided.monitoringDueAt} onChange={(v)=>change(setProvided)('monitoringDueAt',v)} /><Text label="Final report due" type="date" value={provided.reportDueAt} onChange={(v)=>change(setProvided)('reportDueAt',v)} /><Text label="Support/value delivered" area value={provided.supportValueDescription} onChange={(v)=>change(setProvided)('supportValueDescription',v)} /><Button className="md:col-span-2">Record support delivery</Button></form>}
    {step==='monitor'&&<form className="grid gap-3 md:grid-cols-2" onSubmit={(e)=>submit(e,actions.monitor,monitor)}><Text label="Follow-up date" type="date" value={monitor.followUpDate} onChange={(v)=>change(setMonitor)('followUpDate',v)} /><Text label="Production status" value={monitor.productionStatus} onChange={(v)=>change(setMonitor)('productionStatus',v)} /><Text label="Income/market improvement" required={false} value={monitor.incomeMarketImprovement} onChange={(v)=>change(setMonitor)('incomeMarketImprovement',v)} /><Text label="Equipment condition" required={false} value={monitor.equipmentCondition} onChange={(v)=>change(setMonitor)('equipmentCondition',v)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={monitor.problemSolved} onChange={(e)=>change(setMonitor)('problemSolved',e.target.checked)} /> Problem solved</label><Text label="New issues" required={false} value={monitor.newIssues} onChange={(v)=>change(setMonitor)('newIssues',v)} /><Text label="Notes / before-after evidence summary" area required={false} value={monitor.notes} onChange={(v)=>change(setMonitor)('notes',v)} /><Button className="md:col-span-2">Save follow-up</Button></form>}
    {step==='report'&&<form className="grid gap-3 md:grid-cols-2" onSubmit={(e)=>submit(e,actions.report,report)}>{Object.keys(report).map(k=><Text key={k} label={k.replace(/([A-Z])/g,' $1')} area={!['amountValueUsed'].includes(k)} type={k==='amountValueUsed'?'number':'text'} required={k!=='amountValueUsed'} value={report[k]??''} onChange={(v)=>change(setReport)(k,v)} />)}<Button className="md:col-span-2">Submit final report to Admin</Button></form>}
  </section>;
}

export default function ArtisanSupportCases() {
  const casesQuery=useSupportCases();const dashboard=useSupportDashboard();const org=useSupportOrganization();const artisans=useSupportArtisans();const actions=useArtisanSupportMutations();const [selectedId,setSelectedId]=useState(null);const [showCreate,setShowCreate]=useState(false);const [request,setRequest]=useState({artisanUserId:'',problemTitle:'',problemDescription:'',district:'',craft:''});
  const cases=casesQuery.data||[];const selected=cases.find(x=>x.id===selectedId);const approved=org.data?.status==='Approved';
  const create=(e)=>{e.preventDefault();actions.createCase.mutate(request,{onSuccess:()=>setShowCreate(false)});};
  const metrics=dashboard.data?[['Active cases',dashboard.data.activeCases],['Pending inspections',dashboard.data.pendingInspections],['Verified cases',dashboard.data.verifiedCases],['Support in progress',dashboard.data.supportInProgress],['Monitoring',dashboard.data.monitoring],['Reports due',dashboard.data.reportsDue],['Reports submitted',dashboard.data.reportsSubmitted],['Beneficiaries',dashboard.data.beneficiariesSupported]]:[];
  return <div><PageHeader title="Artisan support cases" description="Verify genuine artisans, arrange your organization’s support, monitor outcomes, and report every case to ShilpoHubBD Admin." action={<Button disabled={!approved} onClick={()=>setShowCreate(v=>!v)}>{showCreate?'Cancel':'New case'}</Button>} />
    {!approved&&<div className="mb-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">Organization verification is required before accepting or managing cases. Complete the Organization Profile first.</div>}
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([label,value])=><div key={label} className="rounded-xl border border-border bg-surface p-4"><p className="text-2xl font-semibold text-primary">{value}</p><p className="text-xs text-body/60">{label}</p></div>)}</div>
    <MutationFeedback mutation={actions.createCase} successMessage="Artisan case created." />
    {showCreate&&<form onSubmit={create} className="mb-5 grid gap-3 rounded-xl border border-border bg-surface p-4 md:grid-cols-2"><Labeled label="Artisan"><select aria-label="Artisan" required className={input} value={request.artisanUserId} onChange={(e)=>setRequest(p=>({...p,artisanUserId:e.target.value}))}><option value="">Select artisan</option>{(artisans.data||[]).map(a=><option key={a.id} value={a.id}>{a.name} · {a.detail}</option>)}</select></Labeled>{['problemTitle','district','craft'].map(k=><Text key={k} label={k.replace(/([A-Z])/g,' $1')} value={request[k]} onChange={(v)=>setRequest(p=>({...p,[k]:v}))} required={k==='problemTitle'} />)}<div className="md:col-span-2"><Text label="Problem details" area value={request.problemDescription} onChange={(v)=>setRequest(p=>({...p,problemDescription:v}))} /></div><Button className="md:col-span-2">Create case</Button></form>}
    <AsyncState isLoading={casesQuery.isLoading} isError={casesQuery.isError} error={casesQuery.error}><div className="grid gap-5 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><div className="space-y-2">{cases.map(c=><button type="button" key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full rounded-xl border p-4 text-left ${selectedId===c.id?'border-primary bg-primary/5':'border-border bg-surface'}`}><div className="flex justify-between gap-3"><div><p className="font-semibold text-heading">{c.problemTitle}</p><p className="text-xs text-body/60">{c.caseNumber} · {c.artisanName} · {c.district||'District not set'}</p></div><Badge tone={statusTone(c.status)}>{c.status}</Badge></div>{(c.isFlagged||c.hasDispute)&&<p className="mt-2 text-xs font-semibold text-red-600">⚑ {c.hasDispute?'Artisan dispute':'Flagged'}: {c.flagReason}</p>}</button>)}{!cases.length&&<p className="text-sm text-body/60">No artisan support cases yet.</p>}</div>
      <div>{selected?<><article className="rounded-xl border border-border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">{selected.caseNumber}</p><h2 className="text-xl font-semibold text-heading">{selected.problemTitle}</h2><p className="text-sm text-body/70">{selected.artisanName} · {selected.craft||'Craft not set'} · {selected.district||'District not set'}</p></div><Badge tone={statusTone(selected.status)}>{selected.status}</Badge></div><p className="mt-4 text-sm leading-6">{selected.problemDescription}</p><dl className="mt-4 grid gap-3 text-xs sm:grid-cols-3"><div><dt className="text-body/50">Inspection</dt><dd className="font-semibold">{selected.inspectionResult}</dd></div><div><dt className="text-body/50">Artisan confirmation</dt><dd className="font-semibold">{selected.artisanConfirmation}</dd></div><div><dt className="text-body/50">Report</dt><dd className="font-semibold">{selected.finalReport?.reviewStatus||'Not submitted'}</dd></div></dl>{selected.organizationUserId==null&&<Button className="mt-4" onClick={()=>actions.accept.mutate(selected.id)}>Accept case</Button>}</article>{selected.organizationUserId&&<ActionPanel key={selected.id} selected={selected} actions={actions} />}</>:<div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-body/60">Select a case to inspect and manage it.</div>}</div></div></AsyncState>
  </div>;
}

