import { useEffect, useState } from 'react';
import { PageHeader, Button } from '../../components/ui';
import { useDistricts } from '../../hooks/useDistricts';
import { logisticsPartnersService } from '../../services/logisticsPartnersService';

const emptyPartner = { companyName: '', logoUrl: '', description: '', contactPersonName: '', contactPhone: '', contactEmail: '', baseAddressLine: '', baseCity: '', country: 'Bangladesh', fleetSize: 0, maxDailyPickups: 0, offersCashOnDelivery: true, offersPickup: true, supportsReturns: true, isAcceptingRequests: true, isActive: true };
const emptyArea = { districtId: '', areaName: '', deliveryMethod: 'Standard', standardDeliveryDays: 3, deliveryCharge: 0, pickupAvailable: true, returnSupported: true, isActive: true };
const input = 'rounded-md border border-border bg-background px-3 py-2 text-sm';

export default function AdminLogisticsPartners() {
  const districts = useDistricts(); const [partners, setPartners] = useState([]); const [selected, setSelected] = useState(null);
  const [form, setForm] = useState(emptyPartner); const [area, setArea] = useState(emptyArea); const [performance, setPerformance] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { const page = await logisticsPartnersService.list({ pageSize: 100 }); setPartners(page.items || []); };
  useEffect(() => { load().catch((e) => setError(e.response?.data?.title || e.message)); }, []);
  const choose = async (id) => { try { const [value, stats] = await Promise.all([logisticsPartnersService.getOfficial(id), logisticsPartnersService.performance(id)]); setSelected(value); setPerformance(stats); setForm({ ...emptyPartner, ...value }); } catch (e) { setError(e.response?.data?.title || e.message); } };
  const set = (key) => (e) => setForm((p) => ({ ...p, [key]: e.target.type === 'checkbox' ? e.target.checked : e.target.value }));
  const save = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const payload = { ...form, fleetSize: Number(form.fleetSize), maxDailyPickups: Number(form.maxDailyPickups), baseDistrictId: form.baseDistrictId || null }; const value = selected ? await logisticsPartnersService.updateOfficial(selected.id, payload) : await logisticsPartnersService.createOfficial(payload); setSelected(value); setForm({ ...emptyPartner, ...value }); await load(); } catch (x) { setError(x.response?.data?.title || x.message); } finally { setBusy(false); } };
  const saveArea = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const value = await logisticsPartnersService.upsertOfficialServiceArea(selected.id, { ...area, standardDeliveryDays: Number(area.standardDeliveryDays), deliveryCharge: Number(area.deliveryCharge), surchargeAmount: 0 }); setSelected(value); setArea(emptyArea); await load(); } catch (x) { setError(x.response?.data?.title || x.message); } finally { setBusy(false); } };
  const removeArea = async (id) => { if (!window.confirm('Remove this delivery coverage?')) return; setSelected(await logisticsPartnersService.removeOfficialServiceArea(selected.id, id)); await load(); };
  return <div><PageHeader title="Logistics Partners" description="Official companies, delivery coverage, methods, ETA and charges." />
    {error && <p className="mb-4 rounded-lg border border-danger/30 p-3 text-sm text-danger">{error}</p>}
    <div className="grid gap-6 xl:grid-cols-[320px_1fr]"><section className="rounded-xl border border-border bg-surface p-4"><Button className="mb-4 w-full" onClick={() => { setSelected(null); setForm(emptyPartner); }}>Add partner</Button><div className="space-y-2">{partners.map((p) => <button key={p.id} onClick={() => choose(p.id)} className="w-full rounded-lg border border-border p-3 text-left hover:border-primary"><span className="block font-medium text-heading">{p.companyName}</span><span className="text-xs text-body/60">{p.isActive ? 'Active' : 'Inactive'} · {p.serviceAreaCount} coverage rules</span></button>)}</div></section>
      <div className="space-y-6"><form onSubmit={save} className="grid gap-3 rounded-xl border border-border bg-surface p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-semibold text-heading">{selected ? 'Edit company' : 'New official partner'}</h2>
        {[['companyName','Company name'],['logoUrl','Logo URL'],['contactPersonName','Contact person'],['contactPhone','Phone'],['contactEmail','Email'],['baseCity','Base city'],['baseAddressLine','Base address']].map(([key,label]) => <label key={key} className="flex flex-col gap-1 text-xs text-body/60">{label}<input required={key !== 'logoUrl'} value={form[key] || ''} onChange={set(key)} className={input}/></label>)}
        <label className="flex flex-col gap-1 text-xs text-body/60 sm:col-span-2">Description<textarea value={form.description || ''} onChange={set('description')} className={input}/></label>
        {[['isActive','Active'],['isAcceptingRequests','Accepting deliveries'],['offersPickup','Pickup available'],['supportsReturns','Return delivery']].map(([key,label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form[key])} onChange={set(key)}/>{label}</label>)}
        <Button type="submit" disabled={busy} className="sm:col-span-2">{busy ? 'Saving…' : 'Save partner'}</Button></form>
        {selected && <section className="rounded-xl border border-border bg-surface p-5">{performance && <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4"><div>Total deliveries<br/><strong>{performance.totalDeliveries}</strong></div><div>Success rate<br/><strong>{performance.successRate}%</strong></div><div>ShilpoHub revenue<br/><strong>৳{performance.shilpoHubRevenue}</strong></div><div>Partner revenue<br/><strong>৳{performance.partnerRevenue}</strong></div></div>}<h2 className="mb-3 font-semibold text-heading">Service coverage</h2><div className="mb-4 space-y-2">{selected.serviceAreas.map((a) => <div key={a.id} className="flex justify-between rounded-lg border border-border p-3 text-sm"><span>{a.division} → {a.districtName}{a.areaName ? ` → ${a.areaName}` : ''} · {a.deliveryMethod} · {a.standardDeliveryDays}d · ৳{a.deliveryCharge}</span><button className="text-danger" onClick={() => removeArea(a.id)}>Remove</button></div>)}</div>
          <form onSubmit={saveArea} className="grid gap-3 sm:grid-cols-3"><select aria-label="Coverage district" required value={area.districtId} onChange={(e) => setArea((p) => ({...p,districtId:e.target.value}))} className={input}><option value="">District</option>{(districts.data || []).map((d)=><option key={d.id} value={d.id}>{d.division} → {d.name}</option>)}</select><input aria-label="Coverage upazila or area" placeholder="Upazila / area (blank = district-wide)" value={area.areaName} onChange={(e)=>setArea((p)=>({...p,areaName:e.target.value}))} className={input}/><select aria-label="Delivery method" value={area.deliveryMethod} onChange={(e)=>setArea((p)=>({...p,deliveryMethod:e.target.value}))} className={input}><option>Standard</option><option>Express</option><option>SameDay</option></select><input aria-label="Estimated delivery days" type="number" min="0" placeholder="ETA days" value={area.standardDeliveryDays} onChange={(e)=>setArea((p)=>({...p,standardDeliveryDays:e.target.value}))} className={input}/><input aria-label="Delivery charge" type="number" min="0" step="0.01" placeholder="Charge" value={area.deliveryCharge} onChange={(e)=>setArea((p)=>({...p,deliveryCharge:e.target.value}))} className={input}/><Button type="submit" disabled={busy}>Save coverage</Button></form></section>}
      </div></div></div>;
}
