import { useState } from 'react';
import { AsyncState, Badge, Button, PageHeader } from '../../components/ui';
import MutationFeedback from '../../components/ui/MutationFeedback';
import { useSupportCases, useSupportDashboard, useSupportOrganizations, useSupportOrganizationOptions, useArtisanSupportMutations } from '../../hooks/useArtisanSupport';

const input='rounded-lg border border-border bg-background px-3 py-2 text-sm';
export default function SupportOversight(){const [tab,setTab]=useState('cases');const cases=useSupportCases();const orgs=useSupportOrganizations();const options=useSupportOrganizationOptions();const dashboard=useSupportDashboard();const actions=useArtisanSupportMutations();const [assign,setAssign]=useState({});const [notes,setNotes]=useState({});
 const metrics=dashboard.data?[['Pending organization verification',dashboard.data.pendingOrganizationVerification],['Verified organizations',dashboard.data.verifiedOrganizations],['Active cases',dashboard.data.activeCases],['Reports waiting review',dashboard.data.reportsWaitingReview],['Overdue reports',dashboard.data.overdueReports],['Disputes',dashboard.data.disputes],['Flagged cases',dashboard.data.flaggedCases]]:[];
 return <div><PageHeader title="Artisan support oversight" description="Verify organizations and monitor evidence, disputes, overdue reports and outcomes. Funding decisions remain with each NGO or Government programme." />
 <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([l,v])=><div key={l} className="rounded-xl border border-border bg-surface p-4"><p className="text-2xl font-semibold text-primary">{v}</p><p className="text-xs text-body/60">{l}</p></div>)}</div>
 <div className="mb-4 flex gap-2 border-b border-border">{[['cases','Cases & reports'],['organizations','Organization verification']].map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`border-b-2 px-3 py-2 text-sm font-semibold ${tab===id?'border-primary text-primary':'border-transparent text-body/60'}`}>{l}</button>)}</div>
 {['reviewOrganization','assign','reviewReport','flag'].map(k=><MutationFeedback key={k} mutation={actions[k]} successMessage="Oversight record updated." />)}
 {tab==='organizations'?<AsyncState isLoading={orgs.isLoading} isError={orgs.isError} error={orgs.error}><div className="space-y-3">{(orgs.data||[]).map(o=><article key={o.id} className="rounded-xl border border-border bg-surface p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold text-heading">{o.organizationName}</h2><p className="text-xs text-body/60">{o.organizationType} · Reg. {o.registrationNumber} · {o.registrationAuthority}</p><p className="mt-2 text-sm">{o.organizationDetails}</p><p className="mt-2 text-xs">Representative: {o.representativeName}, {o.representativeDesignation} · {o.officialPhone}</p>{o.registrationDocumentUrl&&<a className="text-xs text-primary underline" href={o.registrationDocumentUrl} target="_blank" rel="noreferrer">Review registration certificate</a>}</div><Badge tone={o.status==='Approved'?'success':'secondary'}>{o.status}</Badge></div>{o.status==='Pending'&&<div className="mt-4 flex flex-wrap gap-2 border-t border-border pt-3"><input aria-label="Organization review note" className={`${input} flex-1`} placeholder="Review note" value={notes[o.id]||''} onChange={e=>setNotes(p=>({...p,[o.id]:e.target.value}))}/><Button onClick={()=>actions.reviewOrganization.mutate({id:o.id,payload:{approved:true,notes:notes[o.id]}})}>Verify</Button><Button variant="secondary" disabled={!notes[o.id]?.trim()} onClick={()=>actions.reviewOrganization.mutate({id:o.id,payload:{approved:false,notes:notes[o.id]}})}>Reject</Button></div>}</article>)}</div></AsyncState>:
 <AsyncState isLoading={cases.isLoading} isError={cases.isError} error={cases.error}><div className="space-y-3">{(cases.data||[]).map(c=><article key={c.id} className={`rounded-xl border bg-surface p-4 ${c.isFlagged||c.hasDispute?'border-red-300':'border-border'}`}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold text-primary">{c.caseNumber}</p><h2 className="font-semibold text-heading">{c.problemTitle}</h2><p className="text-xs text-body/60">{c.artisanName} · {c.organizationName||'Unassigned'} · Report due {c.reportDueAt?new Date(c.reportDueAt).toLocaleDateString():'not set'}</p></div><Badge tone={c.status==='Closed'?'success':'neutral'}>{c.status}</Badge></div><p className="mt-2 text-sm">{c.problemDescription}</p>{c.evidence?.length>0&&<div className="mt-2 flex flex-wrap gap-2">{c.evidence.map(x=><a key={x.id} href={x.fileUrl} target="_blank" rel="noreferrer" className="text-xs text-primary underline">{x.stage}: {x.caption||x.fileName}</a>)}</div>}{(c.isFlagged||c.hasDispute)&&<p className="mt-2 text-sm font-semibold text-red-600">⚑ {c.hasDispute?'Artisan dispute':'Flagged'}: {c.flagReason}</p>}{!c.organizationUserId&&<div className="mt-3 flex flex-wrap gap-2"><select aria-label="Assign verified organization" className={input} value={assign[c.id]||''} onChange={e=>setAssign(p=>({...p,[c.id]:e.target.value}))}><option value="">Assign verified organization</option>{(options.data||[]).map(o=><option key={o.id} value={o.id}>{o.name} · {o.detail}</option>)}</select><Button disabled={!assign[c.id]} onClick={()=>actions.assign.mutate({id:c.id,payload:{organizationUserId:assign[c.id],reportDueAt:new Date(Date.now()+30*86400000).toISOString()}})}>Assign case</Button></div>}{c.finalReport&&c.finalReport.reviewStatus==='WaitingReview'&&<div className="mt-4 rounded-lg bg-primary/5 p-4"><p className="font-semibold">Final report awaiting review</p><p className="mt-1 text-sm">Outcome: {c.finalReport.finalOutcome}</p><textarea aria-label="Report review notes" className={`${input} mt-2 w-full`} placeholder="Review notes / clarification request" value={notes[c.id]||''} onChange={e=>setNotes(p=>({...p,[c.id]:e.target.value}))}/><div className="mt-2 flex gap-2"><Button onClick={()=>actions.reviewReport.mutate({id:c.id,payload:{action:'accept',notes:notes[c.id]}})}>Accept & close</Button><Button variant="secondary" onClick={()=>actions.reviewReport.mutate({id:c.id,payload:{action:'clarify',notes:notes[c.id]}})}>Request clarification</Button><Button variant="secondary" onClick={()=>actions.reviewReport.mutate({id:c.id,payload:{action:'flag',notes:notes[c.id]||'Report requires investigation.'}})}>Flag</Button></div></div>}{!c.finalReport&&c.status!=='Closed'&&<p className="mt-3 text-xs font-medium text-amber-700">This case cannot be resolved until the assigned organization submits its final report.</p>}</article>)}</div></AsyncState>}</div>}


