namespace ShilpoHubBD.Domain.Entities.KnowledgeGraph;

public enum KnowledgeRelationshipType
{
    Creates,
    Practices,
    Produces,
    OperatesIn,
    SpecializesIn,
    LivesIn,
    LocatedIn,
    OriginatesFrom,
    KnownFor,
    Near,
    MadeFrom,
    UsesMaterial,
    UsesTechnique,
    SourcedFrom,
    CelebratedIn,
    AssociatedWith,
    PartOf,
    Represents,
    RelatedTo,
    ParentOf,
    SubtypeOf,
    VariantOf,
    EvolvedFrom,
    BelongsToCategory,
    BelongsTo,
}
